apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-manifest
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: sender-service
              servicePort: 8082
    - http:
        paths:
          - backend:
              serviceName: receiver-service
              servicePort: 8082














