apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-manifest
  namespace: test-namespace
spec:
  rules:
    - host: sender.ru
      http:
        paths:
          - path: /sender
            pathType: Prefix
            backend:
              service:
                name: sender-service
                port:
                  number: 8082
    - host: receiver.ru
      http:
        paths:
          - path: /receiver
            pathType: Prefix
            backend:
              service:
                name: receiver-service
                port:
                  number: 8081
---















