apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender-deployment
  labels:
    app: sender
spec:
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
    spec:
      containers:
        - name: sender-container
          imagePullPolicy: Never
          image: sender
          ports:
            - containerPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver-deployment
  labels:
    app: receiver
spec:
  selector:
    matchLabels:
      app: receiver
  template:
    metadata:
      labels:
        app: receiver
    spec:
      containers:
        - name: receiver-container
          image: receiver
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: sender-service
spec:
  type: NodePort
  selector:
    app: sender
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 31000
---
apiVersion: v1
kind: Service
metadata:
  name: receiver-service
spec:
  type: NodePort
  selector:
    app: receiver
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 32000