apiVersion: apps/v1
kind: Deployment
metadata:
  # название деплоймента
  name: sender-deployment
  labels:
    app: sender-deploy-label
spec:
  # Указывает, с какими подами будет работать деплоймент
  selector:
    #Поды, у которых есть такой label
    matchLabels:
      project: sender-pod
  #Описание подов этого деплоймента
  template:
    metadata:
      #Очевидно, что должны быть такие же labels, какие мы указали в matchLabels в деплойменте
      labels:
        project: sender-pod
    spec:
      #Описываем, какие контейнеры будут в этом поде
      containers:
        - name: sender-container
          image: sender
          # образ никогда не будет скачиваться из-вне, только из имеющихся уже на устройстве локально
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
